subscribepro/subscribepro-magento2-ext

Model/Quote/QuoteItem/SubscriptionCreator.php

This commit sets the customer email notification flag to true when creating a subscription during checkout.

Set when a subscription is created the email flag to true

---

Plugin/ShipperHQ/ShipperMapperPlugin.php
etc/di.xml

Adds ShipperHQ support for subscription shipping groups

Rel 1.0.10

---

Model/Config/ShipperHQ.php
Plugin/ShipperHQ/ShipperMapperPlugin.php
etc/adminhtml/system.xml
etc/config.xml

-Created configuration values for ShipperHQ shipping groups

Rel 1.0.12

---

Helper/DebugLogger.php
Model/Config/Advanced.php
Model/Vault/Form.php
Test/Unit/Model/Vault/FormTest.php
etc/adminhtml/system.xml
etc/config.xml
etc/module.xml

This includes a new debug logger specific for the SubscribePro extension

Rel 1.0.13

---

Api/Data/ProductInterface.php
Api/Data/SubscriptionInterface.php
Api/Data/SubscriptionOptionInterface.php
Block/Cart/Subscription.php
Block/Customer/Subscriptions.php
Block/Vault/Edit/CardExpiration.php
Gateway/Config/Config.php
Gateway/Config/ConfigProvider.php
Gateway/Request/AddressDataBuilder.php
Gateway/Request/CaptureDataBuilder.php
Gateway/Request/CustomerDataBuilder.php
Gateway/Request/OrderDataBuilder.php
Gateway/Request/PaymentDataBuilder.php
Gateway/Request/VaultDataBuilder.php
Gateway/Request/VoidDataBuilder.php
Gateway/Response/TransactionIdHandler.php
Model/CatalogRule/Inspector/BundleProduct.php
Model/Config/Advanced.php
Model/Config/Source/CartRuleCombine.php
Model/Config/Source/LogLevels.php
Model/Config/Source/PaymentAction.php
Model/Product.php
Model/Quote/SubscriptionCreator.php
Model/Subscription.php
Plugin/Product/Configuration.php
Ui/DataProvider/Product/Modifier/Subscription.php

[#144117771]
This fixes the errors in the soap api

Issue 28 fix

---

Api/Data/SubscriptionOptionInterface.php
Model/Quote/SubscriptionOption.php
Model/Rule/Condition/Product.php
etc/di.xml

[#144115633]
Created new cart item rules for subscriptions

Shopping cart discount rules

---

Api/Data/SubscriptionInterface.php
Test/Unit/Platform/Service/SubscriptionTest.php
composer.json

Took away the Subscription REST API's reliance on the Subscribe Pro SDK to define the methods exposed to the API. This decouples the sdk and extension more, and fixes issue 27.

M2 ext issue 27 fix

---

Plugin/Quote/Item.php

[#147697341] Fixes bug with adding a subscription product to the cart as a one-time order multiple times.

---

Api/Data/ProductInterface.php
Api/Data/SubscriptionInterface.php
Model/Product.php
Model/Subscription.php
composer.json

Tested.
Before fix:
After fix:

Fixes #39 - Show subscriptions on My Subs page when configurable or product options are present.

---

Helper/QuoteItem.php
Model/Quote/SubscriptionOption/OptionProcessor.php
composer.json

With these changes, installation and a full subscription life-cycle test works.

Changes for Magento 2.2 compatibility.

---

Plugin/Quote/Item.php
Test/Unit/Helper/QuoteItemTest.php
Test/Unit/Model/Quote/SubscriptionOption/OptionProcessorTest.php
Test/Unit/Plugin/Quote/ItemTest.php

Changes for Magento 2.2 compatibility

[#155187000] Change serialize to json_encode for buyRequest

---

Service/PaymentTokenManagement.php

[#155822547] Update search filters to work with changes in Magento 2.2

---

Block/Customer/Subscriptions.php
Block/Customer/SubscriptionsDirectoryDataProcessor.php
etc/frontend/di.xml
view/frontend/web/js/view/subscription/shipping-info.js

Also fixed a second issue I saw during testing, where the state/region didn't come through on the address.

[#155908785] Show country options in delivery address form on My Subscriptions page

---

composer.json
etc/module.xml

Updated composer dependencies for new versions required by Magento 2.3.

Compatibility with Magento 2.3

---

Block/Customer/Subscriptions.php
Model/Config/Advanced.php
Platform/Tool/Oauth.php
etc/adminhtml/system.xml
etc/config.xml
etc/di.xml
view/frontend/templates/customer/subscriptions.phtml
view/frontend/web/js/view/subscription/list.js

Allows using native or hosted my subscriptions page based on a new setting in the extension configuration. When enabled, additional settings for specifying the widget script URL and JSON configuration are available.

Changes for hosted my subscriptions page

---

Platform/Storage/Product.php
Ui/ConfigProvider/Checkout.php

Removed final keyword from class declaration
Changed md5 to sha256 hash

[#177204867] Two small fixes for EQP

---

Helper/ApplePay/Vault.php
Model/ApplePay/PaymentService.php

- Fix error strlen(null)
- Fix strict function definition.

[#178205036] HotFix - Apple Pay PHP 7.4 compat.

---

README.md

Add coding standards information to README.md

SPRO-44: Define coding / code style standards which we follow in README

---

Helper/ThirdPartyPayment.php
Model/Config/Source/GetPaymentMethodOptions.php
Model/Config/Source/ThirdPartyPaymentMethod.php
Model/Config/ThirdPartyPayment.php
Observer/Checkout/SubmitAllAfter.php
Observer/Payment/Availability.php
Service/OrderCallback/DataBuilder.php
Service/OrderCallback/PlaceOrder.php
etc/adminhtml/system.xml

Introduce Google and Apple payment methods

SPRO-54: Display Google Pay & Apple Pay methods via Adyen

---

Helper/QuoteItem.php
Model/Quote/ItemSubscriptionDiscount.php
Plugin/SalesRule/Validator.php

In for the subscription discount feature to apply discounts in the Magento 2 cart, it will now be required to create a discount rule in Magento admin named **"Subscribe Pro Discount"**.

#152, #145 - Implement new strategy for extending SalesRuleValidator

---

Api/CartManagementInterface.php
Model/Quote/QuoteManagement.php

fix(#158): Fix incorrect typehint types.

---

Model/Quote/QuoteItem/SubscriptionCreator.php
Platform/Manager/Address.php

Pass company with shipping and billing address

---

view/frontend/layout/checkout_index_index.xml

Added configuration for vault to make billing address required

---

Gateway/Response/AuthorizeHandler.php
etc/di.xml

feat: Hot fix for Payment Handler issue
Refs: #210

210 Hot fix

---

etc/config.xml

feat: Change the default config in the hosted configuration.
Refs: #203

#203 Default Configuration to use Hosted My Subscriptions Page

---

view/frontend/layout/vault_cards_listaction.xml

feat: Disable card list page override and "Add New Card" button when payment method disabled.
Refs: #196

#196 When Subscribe Pro payment method is disabled, customer new card ui should also be

---

view/base/requirejs-config.js

Feat: Update `PaymentFields` js lib version in requirejs.
Refs: #197

#197 Update `PaymentFields` js lib version in requirejs.

---

view/frontend/web/js/view/payment/method-renderer/cc-form.js

feat: Add error message on 3DS authentication fails.
Refs: #220

#220 Scenario 3: 3DS2 test card which simulates authentication failure used

---

composer.json

fix: bump dependency for php lib to add 1 time transaction fields

---

view/frontend/web/js/view/vault/card.js

feat: Add payment field validation on the wallet page.
Refs: #197

#197 Work with event validation handler on the wallet page. 

---

Model/Vault/Validator.php
view/frontend/layout/swarming_subscribepro_cards_edit.xml
view/frontend/templates/vault/edit/billing_address.phtml

feat: Make phone number optional on creating new payment card
Refs: #169

#169 Make Phone Number Optional for Adding New Payment Method

---

Controller/Cards/Save.php
Gateway/Request/WalletVoidDataBuilder.php
Gateway/Response/AuthorizeHandler.php
Gateway/Response/WalletVoidHandler.php
etc/di.xml

feat: Change wallet page commands from verify to authorization and void.
Refs: #223

#223 Wallet Page - New Card a/ $N Auth - Use /authorize and /void

---

Service/OrderCallback/DataBuilder.php

feat: Fix placing an order when the payment method is offline.
Refs: #192

#192 Order Callback | Unable to create order when payment method 'checkmo' 

---

Block/Customer/Subscriptions.php
Service/SubscriptionManagement.php

feat: Create a customer if it doesn't exist on my subscription page. Fix issues related to creating dynamic property
Refs: #184

#184 Hosted My Subscriptions | Load hosted my subscriptions regardless if customer found in Subscribe Pro

---

Service/OrderCallback/PlaceOrder.php

feat: Fix partial order mode on the Magento side when the product is not salable
Refs: #167

#167 Order Callback | Support both versions of Partial Order Mode in M2 Order Callback

---

Model/ApplePay/PaymentService.php
etc/csp_whitelist.xml
view/frontend/web/css/source/_module.less
view/frontend/web/js/view/payment/method-renderer/cc-form.js
view/frontend/web/js/view/vault/card.js

feat: Clean up Payment Fields implementation.
Refs: #240

#240 Clean up PaymentFields implementation

---

Model/Config/Advanced.php
Plugin/Payment/PaymentTokenManagement.php
Plugin/Ui/Adminhtml/TokensConfigProvider.php
etc/adminhtml/system.xml
etc/config.xml
etc/di.xml

feat: Added the ability to display expired cards in the account/checkout/admin order page
Refs: #163

#163 Allow option to display Expired cards in admin checkout/frontend checkout

---

Plugin/Sales/Model/Reorder/ReorderPlugin.php
etc/di.xml

feat: Add default cart item options on reorder action.
Refs: #191

#191 Cart price rule issue reported - reorder_ordinal

---

view/adminhtml/web/js/cc.js
view/frontend/web/js/view/payment/method-renderer/cc-form.js
view/frontend/web/js/view/vault/card.js

feat: Pass 6 digits on the admin, wallet and checkout page.
Refs: #248

#248 Pass first 6 digits of card number

---

Gateway/Response/VaultDetailsHandler.php
composer.json

feat: Add Payment token field.
Refs: #250

#250 Use payment token from transaction response instead of from wallet entry / pay profile 

---

etc/adminhtml/system.xml

feat(payments): allow $0 auth on new card on wallet

---

Helper/Vault.php

fix: make handling of transaction credit card exp dates more resilient

---

Block/Adminhtml/Order/Create/Items/Grid.php
Block/Adminhtml/System/Config/TestConnection.php
Block/Customer/SubscriptionsDirectoryDataProcessor.php
Block/Product/Subscription.php
Block/Vault/Edit/CardExpiration.php
Controller/Applepay/PaymentAuthorized.php
Controller/Applepay/ShippingList.php
Gateway/Config/ApplePayConfigProvider.php
Helper/OrderItem.php
Helper/QuoteItem.php
Model/ApplePay/PaymentRequestConfig.php
Model/Rule/Condition/Base.php
Model/Rule/Condition/Interval.php
Plugin/ShipperHQ/ShipperMapperPlugin.php

feat: Fix PHPStan level 1.
Refs: #175

#175 Fix phpstan errors level 1

---

Api/CartManagementInterface.php
Block/Product/Subscription.php
Block/Vault/Edit/BillingAddress.php
Gateway/Command/AbstractCommand.php
Gateway/Command/ApplePay/CaptureStrategyCommand.php
Gateway/Command/CaptureStrategyCommand.php
Gateway/Request/AddressDataBuilder.php
Model/ApplePay/PaymentService.php
Model/Config/Source/CartRuleCombine.php
Model/Config/Source/LogLevels.php
Model/Config/Source/PaymentAction.php
Model/Config/SubscriptionOptions.php
Model/Quote/QuoteItem/SubscriptionCreator.php
Model/Quote/SubscriptionCreator.php
Model/Quote/SubscriptionOption.php
Model/Quote/SubscriptionOption/Updater.php
Model/Subscription.php
Model/Subscription/OptionItem.php
Platform/Manager/Address.php
Platform/Manager/Product.php
Platform/Platform.php
Platform/Service/Address.php
Platform/Service/Product.php
Platform/Service/Subscription.php
Plugin/Product/Configuration.php
Service/SubscriptionManagement.php
Setup/Patch/Data/AddSubscriptionEnabledProductAttributePatch.php

feat: Fix phpstan errors level 3.
Refs: #175

#175 Fix phpstan errors level 3

---

Gateway/Request/AddressDataBuilder.php

feat: Add phone number in the billing address for payment profile.
Refs: #263

#263 Include phone number in billing address when storing payment profile from checkout.

---

Gateway/Config/Config.php
Plugin/CustomerData/InstantPurchasePlugin.php
etc/frontend/di.xml
view/frontend/requirejs-config.js
view/frontend/web/js/view/cart/subscription.js
view/frontend/web/js/view/product/instant-purchase-mixin.js

feat: Add custom functionality to instant purchase functionality.
Refs: #255

#255 Don't display subscribe_pro methods in instant purchase when method not allowed for one-time purchase and not creating a subscription

---

view/frontend/web/css/source/_module.less

feat: Change challenge iframe size.
Refs: #224

#224 3DS2 Challenge content does not fit - Wallet, Checkout

---

Block/Product/Grouped.php
Model/Product/Type/Grouped.php
ViewModel/Grouped.php
etc/frontend/di.xml
view/frontend/layout/catalog_product_view_type_grouped.xml
view/frontend/templates/product/grouped-subscription.phtml
view/frontend/templates/product/view/type/grouped.phtml
view/frontend/web/js/view/product/grouped-subscription.js
view/frontend/web/template/product/grouped-subscription.html

feat: Add subscription functionality on grouped products.
Refs: #207

#207 Create a code example for adding the subscription widget to Subscribe Pro enabled products in a Grouped product.

---

Model/Rule/Condition/Base.php

Fix cart rule issue

---

view/frontend/layout/vault_cards_listaction.xml

Move Add Card button to content container

---

Plugin/ShipperHQ/ShipperMapperPlugin.php

Use Magento quote item class
